cryptomator/ios

- Cryptomator/en.lproj/Localizable.strings
- FileProviderExtensionUI/en.lproj/Localizable.strings
Localizable.strings contains (as most files created by Xcode) an autogenerated comment containing the name of the author who created this file.
These comments are replicated in translated files, which is kind of misleading, since the translation is most likely done by somebody else.
I didn't edit `de.lproj`, as this should get updated by crowdin automatically.
> remove authors from copyright statement in Localizable.strings

- Cryptomator.xcodeproj/project.pbxproj
- Cryptomator/Common/ActionButton.swift
- Cryptomator/Common/ListViewModel.swift
- Cryptomator/VaultList/VaultCell.swift
- Cryptomator/VaultList/VaultInfo.swift
- Cryptomator/VaultList/VaultListViewController.swift
- Cryptomator/VaultList/VaultListViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/FileProviderXPC/FileProviderConnector.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/FileProviderXPC/VaultLocking.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/FileProviderXPC/VaultUnlocking.swift
- CryptomatorFileProvider/FileProviderAdapterManager.swift
- CryptomatorTests/VaultListViewModelTests.swift
- FileProviderExtension/FileProviderExtension.swift
- FileProviderExtension/VaultLockingServiceSource.swift
- FileProviderExtension/VaultUnlockingServiceSource.swift
- FileProviderExtensionUI/FileProviderCoordinator.swift
- FileProviderExtensionUI/Info.plist
- FileProviderExtensionUI/RootViewController.swift
- FileProviderExtensionUI/UnlockVaultViewController.swift
- FileProviderExtensionUI/UnlockVaultViewModel.swift
This introduces the feature to manually lock a vault in the main app (in the vault list). 
This is done analogously to the unlocking in the `FileProviderExtensionUI` (see #59), via an XPC connection with the `FileProviderExtension`.
> Manually locking a vault in the main app

- Cryptomator.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Cryptomator/Common/CloudAccountList/AccountListViewModel.swift
- Cryptomator/Common/CloudAuthenticator.swift
- Cryptomator/VaultDetail/VaultDetailInfoFooterViewModel.swift
- Cryptomator/VaultDetail/VaultDetailViewModel.swift
- Cryptomator/WebDAV/WebDAVAuthenticationViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/CryptomatorDatabase.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/CloudProviderDBManager.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/VaultAccountDBManager.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/VaultAccountManagerError+Localization.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/WebDAV/WebDAVAuthenticator+Keychain.swift
- CryptomatorCommon/Tests/CryptomatorCommonCoreTests/Manager/VaultManagerTests.swift
- CryptomatorCommonHostedTests/Keychain/WebDAVKeychainTests.swift
- FileProviderExtension/FileProviderExtension.swift
- SharedResources/en.lproj/Localizable.strings
This PR fixes #41 by preventing the creation of vault duplicates and cloud provider account duplicates.
A vault duplicate is a vault that has the same vault path and the same cloud provider account as an already added vault.
This has been fixed by changing the database scheme.
Most cloud providers have already handled it correctly when the user logs into the same account, i.e. no error is displayed to the user and he can continue the process (e.g. add a vault) but no new cloud provider account is created in the database.
Now this is also the case with WebDAV and Google Drive, where previously a new cloud provider account has been created in the database.
We define a WebDAV credential duplicate as a WebDAV credential with the same `baseURL` and `username`.
> Bugfix: prevent vault and cloud provider account duplicates

- Cryptomator.xcodeproj/project.pbxproj
- Cryptomator/Common/CloudAccountList/AccountListViewController.swift
- Cryptomator/Settings/SettingsCoordinator.swift
- Cryptomator/Settings/SettingsViewController.swift
- Cryptomator/Settings/SettingsViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/CryptomatorUserDefaults.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/FileProviderXPC/LogLevelUpdating.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/LoggerSetup.swift
- CryptomatorFileProvider/LogLevelUpdatingServiceSource.swift
- CryptomatorFileProviderTests/LogLevelUpdatingServiceSourceTests.swift
- CryptomatorTests/FileProviderConnectorMock.swift
- CryptomatorTests/SettingsViewModelTests.swift
- CryptomatorTests/VaultListViewModelTests.swift
- FileProviderExtension/FileProviderExtension.swift
- SharedResources/en.lproj/Localizable.strings
The settings screen was created as specified in #9, with the exception that iCloud Drive is not listed under "Cloud Services".
This is because we cannot log the user out of their Apple ID directly from the app, moreover it is questionable whether the user would be aware of the implications of this decision.
Debug mode is automatically enabled for debug builds, so to test disabling debug mode, the preprocessor macro block in `CryptomatorUserDefaults` must be commented out.
> Added Screen: Settings

- Cryptomator.xcodeproj/project.pbxproj
- Cryptomator/AddVault/CreateNewVault/CreateNewVaultPasswordViewController.swift
- Cryptomator/AddVault/CreateNewVault/CreateNewVaultPasswordViewModel.swift
- Cryptomator/AddVault/CreateNewVault/SetVaultNameViewController.swift
- Cryptomator/AddVault/CreateNewVault/SetVaultNameViewModel.swift
- Cryptomator/AddVault/OpenExistingVault/OpenExistingVaultPasswordViewController.swift
- Cryptomator/AddVault/OpenExistingVault/OpenExistingVaultPasswordViewModel.swift
- Cryptomator/Common/Cells/ReturnButtonSupport.swift
- Cryptomator/Common/Cells/TextFieldCell.swift
- Cryptomator/Common/Cells/TextFieldCellViewModel.swift
- Cryptomator/Common/ChooseFolder/CreateNewFolderViewController.swift
- Cryptomator/Common/ChooseFolder/CreateNewFolderViewModel.swift
- Cryptomator/VaultDetail/ChangePassword/ChangePasswordViewController.swift
- Cryptomator/VaultDetail/ChangePassword/ChangePasswordViewModel.swift
- Cryptomator/VaultDetail/RenameVault/RenameVaultViewController.swift
- Cryptomator/VaultDetail/VaultDetailUnlockVaultViewController.swift
- Cryptomator/VaultDetail/VaultDetailUnlockVaultViewModel.swift
- Cryptomator/WebDAV/WebDAVAuthenticationViewController.swift
- Cryptomator/WebDAV/WebDAVAuthenticationViewModel.swift
- CryptomatorTests/ChangePasswordViewModelTests.swift
- CryptomatorTests/CreateNewFolderViewModelTests.swift
- CryptomatorTests/SetVaultNameViewModelTests.swift
- CryptomatorTests/XCTest+Combine.swift
- FileProviderExtensionUI/UnlockVaultViewController.swift
This PR adds the feature to navigate through the different `UITextFields` within a ViewModel using the return button.
If the return button is pressed at the last `UITextField`, this is communicated to the respective `UIViewController` via the `lastReturnButtonPressed` publisher, so that it can execute the same method as when the `rightBarButtonItem` is pressed.
> Feature: Use return button to navigate through UITextFields

- Cryptomator/Common/Cells/SwitchCell.swift
- Cryptomator/Settings/SettingsViewController.swift
- Cryptomator/Settings/SettingsViewModel.swift
- CryptomatorTests/SettingsViewModelTests.swift
- SharedResources/en.lproj/Localizable.strings
In the settings screen an alert is now displayed if the user wants to activate the debug mode and he has to explicitly confirm it again to actually activate the debug mode. 
The alert informs the user that sensitive data like filenames and paths (but no passwords or cookies) may be written to the log files.
> Added additional confirmation of enabling debug mode

- Cryptomator/Common/Cells/TextFieldCell.swift
- Cryptomator/WebDAV/WebDAVAuthenticating.swift
- Cryptomator/WebDAV/WebDAVAuthenticationCoordinator.swift
- Cryptomator/WebDAV/WebDAVAuthenticationViewController.swift
- Cryptomator/WebDAV/WebDAVAuthenticationViewModel.swift
- SharedResources/en.lproj/Localizable.strings
Allows the user to connect via HTTP to a WebDAV service.
The user must explicitly agree that they are aware of the risks of using an HTTP connection. In addition, the user has the option to directly change the URL scheme from HTTP to HTTPS. 
This fixes #109.
> Feature: Allow HTTP for WebDAV connection

- Cryptomator/AddVault/ChooseCloudViewController.swift
- Cryptomator/AddVault/CreateNewVault/CreateNewVaultCoordinator.swift
- Cryptomator/AddVault/CreateNewVault/CreateNewVaultPasswordViewController.swift
- Cryptomator/AddVault/CreateNewVault/LocalVault/CreateNewLocalVaultCoordinator.swift
- Cryptomator/AddVault/CreateNewVault/LocalVault/CreateNewLocalVaultViewModel.swift
- Cryptomator/AddVault/LocalVault/LocalFileSystemAuthenticationViewController.swift
- Cryptomator/AddVault/LocalVault/LocalFileSystemAuthenticationViewModel.swift
- Cryptomator/AddVault/OpenExistingVault/LocalVault/OpenExistingLocalVaultCoordinator.swift
- Cryptomator/AddVault/OpenExistingVault/LocalVault/OpenExistingLocalVaultViewModel.swift
- Cryptomator/AddVault/OpenExistingVault/OpenExistingVaultCoordinator.swift
- Cryptomator/AppDelegate.swift
- Cryptomator/Common/CloudAuthenticator.swift
- Cryptomator/Common/CloudProviderType+Localization.swift
- Cryptomator/Common/UIImage+CloudProviderType.swift
- Cryptomator/Settings/SettingsCoordinator.swift
- Cryptomator/VaultDetail/MoveVault/MoveVaultViewModel.swift
- Cryptomator/VaultDetail/VaultDetailViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/CryptomatorDatabase.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/CloudProviderAccountDBManager.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/CloudProviderType.swift
- CryptomatorTests/AddLocalVault/CreateNewLocalVaultViewModelTests.swift
- CryptomatorTests/AddLocalVault/OpenExistingLocalVaultViewModelTests.swift
- CryptomatorTests/CreateNewVaultPasswordViewModelTests.swift
- CryptomatorTests/DatabaseManagerTests.swift
- CryptomatorTests/MoveVaultViewModelTests.swift
- CryptomatorTests/RenameVaultViewModelTests.swift
- CryptomatorTests/VaultListViewModelTests.swift
This PR adds the option for iCloud Drive to the `ChooseCloud` screen and thus fixes #40.
The `CloudProviderType` now has underlying Types for WebDAV and LocalFileSystem, which refines the respective `CloudProviderType` (e.g. in `custom` and `iCloudDrive`) and thus enables further presets for the `ChooseCloud` screen.
This change to the `CloudProviderType` requires a migration of the existing database.
We did not nuke the database via GRDB this time, because this has the disadvantage that users of early TestFlight versions may have problems installing the release version.
For the TestFlight versions before the initial App Store release we did not migrate the database.
However, since we only nuke the database for TestFlight versions when making schema changes, this can lead to an incorrect …
> Feature: iCloud Drive as option in the `ChooseCloud` screen

- Cryptomator.xcodeproj/project.pbxproj
- Cryptomator.xcodeproj/xcshareddata/xcschemes/Snapshots.xcscheme
- Cryptomator/AppDelegate.swift
- Cryptomator/Snapshots/SnapshotCoordinator.swift
- Cryptomator/Snapshots/SnapshotVaultListViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/VaultPasswordManager.swift
- CryptomatorCommon/Tests/CryptomatorCommonCoreTests/Manager/VaultManagerTests.swift
- CryptomatorCommonHostedTests/Keychain/VaultPasswordKeychainManagerTests.swift
- CryptomatorTests/VaultListViewModelTests.swift
- FileProviderExtension/FileProviderExtension.swift
- FileProviderExtension/Snapshots/FileProviderEnumeratorSnapshotMock.swift
- FileProviderExtension/Snapshots/VaultUnlockingServiceSourceSnapshotMock.swift
- FileProviderExtensionUI/FileProviderCoordinator.swift
- FileProviderExtensionUI/RootViewController.swift
- FileProviderExtensionUI/Snapshots/FileProviderCoordinatorSnapshotMock.swift
- FileProviderExtensionUI/UnlockVaultViewModel.swift
- SharedResources/en.lproj/Localizable.strings
- Snapshots/SnapshotHelper.swift
- Snapshots/Snapshots.swift
- fastlane/Fastfile
- fastlane/README.md
- fastlane/Snapfile
This PR enables the automatic creation of snapshots via fastlane.
As we mock some data for the snapshots, we use the active compilation conditions `SNAPSHOTS` in order to not pollute the normal code base.
The active compilation condition will be set automatically when running `fastlane snapshot`.
However, if one wants to run the snapshot UI tests via Xcode, one has to manually add `SNAPSHOTS` to the active compilation conditions of each involved target (currently: `Cryptomator`, `FileProviderExtension` and `FileProviderExtensionUI`).
> Feature: Added support for fastlane snapshot

- Cryptomator/Purchase/PurchaseCoordinator.swift
- Cryptomator/Purchase/PurchaseViewModel.swift
- CryptomatorTests/Purchase/PurchaseViewModelTests.swift
- SharedResources/en.lproj/Localizable.strings
This PR adds a more detailed description regarding the upgrade from Cryptomator 1.x to the purchase screen.
Instead of displaying the _Upgrade from Cryptomator 1.x_ button only when a user is eligible for an upgrade because he has installed the current version of Cryptomator 1.x, it is now displayed to every user.
In addition, the user is informed that if they have already purchased an older version of Cryptomator, they must update it or download it again from the App Store. 
These changes were necessary because some users thought they had to tap _Restore Purchase_ if they had already purchased Cryptomator 1.x and wanted to unlock the full version.
> Added a more detailed description about upgrading from the legacy app

- Cryptomator/AppDelegate.swift
- Cryptomator/Common/BaseNavigationController.swift
- Cryptomator/Common/Bindable.swift
- Cryptomator/Common/HeaderFooter/AttributedTextHeaderFooterView.swift
- Cryptomator/Common/HeaderFooter/BaseHeaderFooterView.swift
- Cryptomator/Common/ListViewController.swift
- Cryptomator/MainCoordinator.swift
- Cryptomator/Snapshots/SnapshotCoordinator.swift
- Cryptomator/Snapshots/SnapshotVaultListViewModel.swift
- Cryptomator/VaultDetail/VaultDetailCoordinator.swift
- Cryptomator/VaultDetail/VaultDetailViewController.swift
- Cryptomator/VaultDetail/VaultDetailViewModel.swift
- Cryptomator/VaultList/VaultCellViewModel.swift
- Cryptomator/VaultList/VaultInfo.swift
- Cryptomator/VaultList/VaultListViewController.swift
- Cryptomator/VaultList/VaultListViewModel.swift
- CryptomatorTests/VaultListViewModelTests.swift
- Snapshots/Snapshots.swift
The vault list is now displayed in a `UISplitViewController`, which allows us on the iPad to display the vault list on the left side of the screen and, if selected, the associated vault detail screen on the right side.
The flickering of the footer texts in the vault detail screen has also been fixed.
> Feature: Improved ipad support for vault list

- Cryptomator.xcodeproj/project.pbxproj
- Cryptomator/Snapshots/SnapshotCoordinator.swift
- FileProviderExtensionUI/Snapshots/FileProviderCoordinatorSnapshotMock.swift
- Snapshots/SnapshotBiometrics.h
- Snapshots/SnapshotBiometrics.m
- Snapshots/Snapshots-Bridging-Header.h
- Snapshots/Snapshots.swift
Adds the ability to display the correct biometric authentication (Touch ID or Face ID) for the device to the screenshot mocks.
This is done by enrolling the simulator programmatically for biometric authentication by setting  `com.apple.BiometricKit.enrollmentChanged` to `true` via a Darwin notification (see this [blog post](https://medium.com/kinandcartacreated/so-you-want-to-automate-ios-biometrics-81bd015f5d38) and the corresponding [repository](https://github.com/KaneCheshire/BiometricAutomationDemo) for more details).
> Feature: Show device-specific enrolled biometrics within snapshots

- Cryptomator.xcodeproj/project.pbxproj
- CryptomatorFileProvider/FileProviderAdapter.swift
- CryptomatorFileProvider/FileProviderAdapterManager.swift
- CryptomatorFileProvider/FileProviderNotificator.swift
- CryptomatorFileProvider/FileProviderNotificatorManager.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterStartProvidingItemTests.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterTestCase.swift
- CryptomatorFileProviderTests/FileProviderAdapterManagerTests.swift
- CryptomatorFileProviderTests/Mocks/FileProviderItemUpdateDelegateMock.swift
- CryptomatorFileProviderTests/Mocks/FileProviderNotificatorManagerMock.swift
- CryptomatorFileProviderTests/Mocks/FileProviderNotificatorMock.swift
- FileProviderExtension/FileProviderEnumerator.swift
- FileProviderExtension/FileProviderExtension.swift
- FileProviderExtension/VaultLockingServiceSource.swift
This PR prevents previously viewed items from being visible in the Siri search and thus fixes #153.
To counter timing issues, whenever the working set gets refreshed, all `NSFileProviderItemIdentifiers` of the items called since the last lock are removed from the working set. 
Additionally, the complete cache of the working set is invalidated as soon as the vault gets locked.
> Bugfix: remove item from working set after `startProvidingItem` has been called

- Cryptomator/AddVault/CreateNewVault/SetVaultNameViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/ItemNameValidator.swift
- CryptomatorCommon/Tests/CryptomatorCommonCoreTests/ItemNameValidatorTests.swift
- CryptomatorFileProvider/FileProviderAdapter.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterMoveItemTests.swift
- CryptomatorTests/SetVaultNameViewModelTests.swift
- SharedResources/en.lproj/Localizable.strings
Fixes  #152.
The validation of the vault name and a general FileProvider item has been unified.
Small background info on the error display in the Files app:
In the FileProviderExtension only errors with `NSFileProviderErrorDomain` or `CocoaErrorDomain` are displayed and (meaningfully) processed. In this case we can override the `localizedErrorDescription` of the `CocoaError.fileWriteInvalidFileName` to display our own error messages.
Additionally, we set the `localizedFailureReason` to an empty string to mimic the default alert message style from the Files app.
> Bugfix: disallow certain special characters in item names

- CryptomatorCommon/Sources/CryptomatorCommonCore/CryptomatorDatabase.swift
Fixes #171 by bypassing the regression introduced by SQLite 3.37.0 by accepting double-quoted string literals.
Since iOS 15.4 uses a newer SQLite version (3.37.x instead of 3.36.x), this caused a crash on pending migration.
More details can be found in the related [issue](https://github.com/groue/GRDB.swift/issues/1171) at the GRDB repository.
The following scenarios have been successfully tested:
- fully migrated database
- clean installation, i.e. database is created from scratch
- database has not yet been migrated to v2
- empty v1 database
- with a cached vault (but here without reopening the Files app, because the database was copied between the simulators and therefore the matching FileProviderDomain is missing)
> Workaround for a regression introduced with SQLite 3.37.0

- Cryptomator.xcodeproj/project.pbxproj
- Cryptomator.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Cryptomator/AppDelegate.swift
- Cryptomator/MainCoordinator.swift
- Cryptomator/Purchase/PremiumManager.swift
- Cryptomator/Purchase/PurchaseViewController.swift
- Cryptomator/Purchase/PurchaseViewModel.swift
- Cryptomator/Purchase/StoreManager.swift
- Cryptomator/Purchase/StoreObserver.swift
- Cryptomator/Settings/SettingsCoordinator.swift
- Cryptomator/Settings/SettingsViewController.swift
- Cryptomator/Settings/SettingsViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/CryptomatorUserDefaults.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/FullVersionChecker.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Mocks/CryptomatorSettingsMock.swift
- CryptomatorCommon/Tests/CryptomatorCommonCoreTests/FullVersionCheckerTests.swift
- CryptomatorFileProviderTests/LogLevelUpdatingServiceSourceTests.swift
- CryptomatorTests/Mocks/PremiumManagerMock.swift
- CryptomatorTests/Purchase/PurchaseViewModelTests.swift
- CryptomatorTests/Purchase/StoreObserverTests.swift
- SharedResources/en.lproj/Localizable.strings
- StoreKitTestConfiguration/Configuration.storekit
Adds the option to use an annual subscription instead of a one-time Lifetime Premium purchase. In particular, this allows the use (starting with iOS 14) of [Offer Codes](https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/subscriptions_and_offers/implementing_offer_codes_in_your_app).
To support subscriptions, it is necessary to use or read the in-app purchase receipt.
This can be done in two ways:
1. by using your own server / 3rd party provider.
2. locally on the device
The advantage of option 1 is that we are notified when the user has cancelled the subscription.
However, option 1 has the disadvantage that we have to create additional infrastructure and it contradicts our general approach of "do everything on the local device".
Therefore, we decided to …
> Feature: subscription & offer codes

- Cryptomator.xcodeproj/project.pbxproj
- CryptomatorFileProvider/FileProviderAdapter.swift
- CryptomatorFileProvider/FileProviderAdapterManager.swift
- CryptomatorFileProvider/FileProviderEnumerator.swift
- CryptomatorFileProvider/LocalURLProviderType.swift
- CryptomatorFileProvider/VaultUnlockingServiceSource.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterCreateDirectoryTests.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterDeleteItemTests.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterImportDocumentTests.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterStartProvidingItemTests.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterTestCase.swift
- CryptomatorFileProviderTests/FileProviderAdapterManagerTests.swift
- CryptomatorFileProviderTests/FileProviderEnumeratorTests.swift
- CryptomatorFileProviderTests/Mocks/FileProviderAdapterProvidingMock.swift
- CryptomatorFileProviderTests/Mocks/LocalURLProviderMock.swift
- FileProviderExtension/FileProviderExtension.swift
Since the bug with the strong reference to the FileProviderExtension was fixed in https://github.com/cryptomator/ios/commit/f77da62827eec74929d4f9dce50a3be34d047b41, the FileProviderExtension now actually deinitializes itself. Since we had only a weak reference in the FileProviderAdapter on the FileProviderExtension object, we received thereby after some time no more local URLs. This caused all actions that call `importDocument` to fail.
Therefore, this should fix #181 , #179 and maybe even #173.
> Fixed missing localURLProvider

- Cryptomator/Purchase/PurchaseFooterView.swift
- Cryptomator/Purchase/PurchaseViewController.swift
- Cryptomator/Purchase/PurchaseViewModel.swift
- Cryptomator/Settings/SettingsViewController.swift
- Cryptomator/Settings/SettingsViewModel.swift
- SharedResources/en.lproj/Localizable.strings
Since the code redemption sheet does not reliably provide (internal) feedback about a successful redemption or cancellation of the process (as is the case with a normal purchase of an in-app product), we have decided to remove the Redeem Code button from the Purchase Screen. In our opinion, this offers a better user experience, as it is still possible to redeem offer codes via the app store or via direct URLs and they can be reliably recognized via the app store receipt.
> Removed the redeem code button from the purchase screen

- Cryptomator.xcodeproj/project.pbxproj
- Cryptomator/Settings/SettingsViewModel.swift
- Cryptomator/VaultDetail/ChangePassword/ChangePasswordViewModel.swift
- Cryptomator/VaultDetail/KeepUnlocked/VaultKeepUnlockedViewModel.swift
- Cryptomator/VaultDetail/MoveVault/MoveVaultViewModel.swift
- Cryptomator/VaultDetail/VaultDetailViewModel.swift
- Cryptomator/VaultList/VaultCellViewModel.swift
- Cryptomator/VaultList/VaultListViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/FileProviderXPC/FileProviderConnector.swift
- CryptomatorFileProvider/FileProviderEnumerator.swift
- CryptomatorFileProvider/FileProviderNotificator.swift
- CryptomatorFileProviderTests/FileProviderEnumeratorTests.swift
- CryptomatorFileProviderTests/FileProviderNotificatorTests.swift
- CryptomatorFileProviderTests/WorkingSetEnumerationTests.swift
- CryptomatorTests/ChangePasswordViewModelTests.swift
- CryptomatorTests/FileProviderConnectorMock.swift
- CryptomatorTests/MoveVaultViewModelTests.swift
- CryptomatorTests/RenameVaultViewModelTests.swift
- CryptomatorTests/SettingsViewModelTests.swift
- CryptomatorTests/VaultKeepUnlockedViewModelTests.swift
- CryptomatorTests/VaultListViewModelTests.swift
- FileProviderExtension/FileProviderExtension.swift
- FileProviderExtensionUI/UnlockVaultViewModel.swift
Limits the background activity of the FileProviderExtension and thus fixes #206.
Due to the invalidation of the working set introduced in #156  a new enumeration of the working set was periodically triggered by the Files app in the case of a locked vault. This led to increased and unnecessary background activity of the FileProviderExtension.
This has now been fixed as follows:
When a vault is locked, the working set is invalidated once - this updates the sync anchor, which now has the invalidated flag set. If a subsequent `enumerateChanges(for:from:)` for the sync anchor fails with the invalidated flag set, the working set is not invalidated again, but the Files app is simply informed that there were no changes to the working set. This breaks the loop and the next time the vault is …
> Bugfix: Limit the background activity of the FileProviderExtension

- .github/workflows/build.yml
- FileProviderExtensionUI/FileProviderCoordinator.swift
- FileProviderExtensionUI/UnlockVaultViewController.swift
- FileProviderExtensionUI/UnlockVaultViewModel.swift
- Scripts/process.sh
Performs a quick unlock, i.e. biometric authentication gets triggered immediately and thus fixes #225.
If the biometric authentication has failed several times, the user is shown "Enter password" as a fallback option - this is possible from iOS 16 and later, because Apple fixed a bug in iOS 16 which caused the FileProviderExtensionUI to close too early during biometric authentication. In this case, the regular unlock screen will be shown.
> Feature:  Support for quick unlock

- Cryptomator/Common/CloudAccountList/AccountListViewModel.swift
When the account list for Dropbox or pCloud is called and no account is available, the empty account list message flickers once. This is due to the fact that until now, even though no account was available, it still tried to retrieve info online for an empty account list. This caused that the table view was notified about the empty account list a second time. 
Therefore, it is now checked if the account list is empty before performing such a query, which prevents the table view from being notified about the empty account list again. Thus, this fixes #235.
> Bugfix: Prevent flickering when Dropbox or pCloud account list is empty 

- Cryptomator.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Cryptomator/Common/CloudAccountList/AccountListViewModel.swift
- Cryptomator/Common/DatabaseManager.swift
- Cryptomator/VaultDetail/VaultDetailViewModel.swift
- Cryptomator/VaultList/VaultListViewModel.swift
- CryptomatorCommon/Package.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/CloudProviderAccountDBManager.swift
- CryptomatorFileProvider/DB/WorkingSetObserver.swift
The following dependencies have been updated:
- cloud-access-swift (from `1.3.0` to `1.4.0`)
- GRDB (from `4.14.0` to `5.25.0`)
For the major update from GRDB 4 to GRDB 5, only changes regarding the ValueObservations were necessary. Because they now have a different runtime behavior (for more details see the [official GRDB 5 Migration Guide](https://github.com/groue/GRDB.swift/blob/e02f2c8abacff2799ed14926edcbf6e76fb9f805/Documentation/GRDB5MigrationGuide.md#runtime-behavior-of-valueobservation)).
> Updated dependencies

- CryptomatorFileProvider/DB/ItemMetadataDBManager.swift
In detail, two optimizations were made:
- `cacheMetadata(itemMetadataList:)` now uses a [UPSERT](https://www.sqlite.org/lang_UPSERT.html) instead of a manual fetch and subsequent match.
- `flagAllItemsAsMaybeOutdated(withParentID:)`now updates the entire request at once instead of iterating through each individual item.
Both optimizations take advantage of SQLite's standard features instead of using more inefficient "workarounds" in Swift.
Furthermore, both optimizations lead to a smaller memory footprint and are thus relevant for #232.
> `ItemMetadataDBManager` improvements

- Cryptomator.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Cryptomator/AddVault/CreateNewVault/CreateNewVaultCoordinator.swift
- Cryptomator/AddVault/LocalVault/LocalFileSystemAuthenticationViewModel.swift
- Cryptomator/AddVault/OpenExistingVault/OpenExistingVaultCoordinator.swift
- CryptomatorCommon/Package.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/CloudProviderDBManager.swift
Adds support for limiting the page size of fetchItemList in the main app for the changes introduced with https://github.com/cryptomator/cloud-access-swift/pull/14.
For the FileProviderExtension the max page size is set to 500, which ensures that not too many items are processed at once and thus fixes the memory limit described in #232.
An important note is that the Files app still requests all items of a folder. This means that the user may have to wait a very long time before seeing the items of a folder with a large number of items. According to Apple, this is the expected behavior and can only be fixed with a workaround via the working set. However, we have decided not to implement this workaround for now, as we are currently not implementing other workarounds via the working set due …
> Added support for limiting the page size of fetchItemList

- Cryptomator/Common/DatabaseManager.swift
- Cryptomator/VaultDetail/MoveVault/MoveVaultCoordinator.swift
The vault list flickered briefly when the app was launched if the list was empty. This happened because the database observer outputs duplicates (in this case two times an empty array). Therefore, successive duplicates are now removed during database observation.
> Bugfix: Prevent flickering when vault list is empty

- Cryptomator/S3/S3AuthenticationViewController.swift
- Cryptomator/WebDAV/WebDAVAuthentication.swift
- Cryptomator/WebDAV/WebDAVAuthenticationViewController.swift
On iOS 14 `viewDidLoad` gets not called when subclassing `HostingViewController`.
As we used the `viewDidLoad` for setting the title, navigationItems and setting up the bindings this leads to errors (see #280).
This PR fixes these problems and thus closes #280 by using a standard `UIViewController` and just embed the view of the `HostingViewController`.
Furthermore, the appearance of the `WebDAVAuthentication` Screen has been updated for iOS 14 to be also `insetGrouped`.
> Bugfix: Fix iOS 14 SwiftUI HostingViewController missing Navigation Items

- Cryptomator/WebDAV/WebDAVAuthentication.swift
- Cryptomator/WebDAV/WebDAVAuthenticationViewController.swift
Fixes the issue #295  where the untrusted TLS certificate wasn't shown to the user because of the currently presented ProgressHUD.
> Bugfix: Show untrusted TLS certificate alert

- CryptomatorFileProvider/FileProviderAdapter.swift
We introduced with #293 the progress reporting for Download & Upload for WebDAV. However, it seems like the FileProviderExtension doesn't like when one registers a already running URLSessionTask and this could trigger `EXC_RESOURCE RESOURCE_TYPE_MEMORY`. Somehow registering and then resuming the task seem to fix this issue (and thus closing #299)… which is a bit unexpected but the documentation inside the header file of NSFileProvideManager (but not the online [documentation](https://developer.apple.com/documentation/fileprovider/nsfileprovidermanager/2890932-register)) also states:
> The task must be suspended at the time of calling.
So I guess we are interacting now a bit more according to the specifications.
> Manually resume URLSessionTask after it has been successfully registered

- Cryptomator/AddVault/AddVaultCoordinator.swift
- Cryptomator/AppDelegate.swift
- Cryptomator/Onboarding/OnboardingCoordinator.swift
- Cryptomator/VaultList/VaultListViewController.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/CryptomatorUserDefaults.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/FullVersionChecker.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Mocks/FullVersionCheckerMock.swift
- CryptomatorCommon/Tests/CryptomatorCommonCoreTests/FullVersionCheckerTests.swift
- CryptomatorFileProvider/FileProviderAdapter.swift
- CryptomatorFileProvider/FileProviderItem.swift
- CryptomatorFileProvider/RootFileProviderItem.swift
- CryptomatorFileProvider/ServiceSource/FileImportingServiceSource.swift
- CryptomatorFileProviderTests/FileImportingServiceSourceTests.swift
- CryptomatorFileProviderTests/FileProviderAdapter/FileProviderAdapterTestCase.swift
- CryptomatorFileProviderTests/FileProviderAdapterManagerTests.swift
- CryptomatorFileProviderTests/FileProviderEnumeratorTests.swift
- CryptomatorFileProviderTests/FileProviderItemTests.swift
- CryptomatorFileProviderTests/Middleware/TaskExecutor/CloudTaskExecutorTestCase.swift
- CryptomatorFileProviderTests/ServiceSource/CacheManagingServiceSourceTests.swift
- FileProviderExtension/FileProviderExtension.swift
Updates `CryptomatorSettings` and the `FullVersionChecker` to use the recently introduced dependency injection framework.
Please test:
- existing full version via IAP gets still correctly recognized (Main App & FileProvider)
- debug mode can be enabled / disabled and internally works
- the always premium version works as expected
> Inject FullVersionChecker with new DI framework

- .github/workflows/build.yml
Due to the recent issues where it was forgotten to update some code related to the `ALWAYS_PREMIUM `compilation condition in #323, I thought it might make sense to also run the build & test steps for the Premium version as well.
This would allow us to catch compilation issues related the premium version earlier. 
Also those jobs run in parallel so the additional overhead should be minimal.
> Run build & test also for Premium configuration

- .github/SUPPORT.md
Fix typo issue at .github/SUPPORT.md from `decissions` to `decisions`
> Fix typo issue at .github/SUPPORT.md

- Cryptomator.xcodeproj/project.pbxproj
- Cryptomator/Snapshots/SnapshotCoordinator.swift
- Cryptomator/VaultList/VaultCellViewModel.swift
- Cryptomator/VaultList/VaultListViewModel.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/FileProviderXPC/VaultLocking.swift
- CryptomatorCommon/Sources/CryptomatorCommonCore/Promise+AllIgnoringResult.swift
- CryptomatorCommon/Tests/CryptomatorCommonCoreTests/Promise+AllIgnoringResultsTests.swift
- CryptomatorCommon/Tests/CryptomatorCommonCoreTests/XCTestCase+Promises.swift
- CryptomatorFileProvider/FileProviderAdapterManager.swift
- CryptomatorFileProvider/ServiceSource/VaultLockingServiceSource.swift
- CryptomatorFileProvider/Workflow/WorkflowDependencyFactory.swift
- CryptomatorFileProviderTests/FileProviderAdapterManagerTests.swift
- CryptomatorFileProviderTests/Mocks/FileProviderAdapterCacheTypeMock.swift
- CryptomatorTests/VaultListViewModelTests.swift
This pull request fixes the issue described in bug ticket #346, where the lock icons are missing in the vaults list after iOS 17.4 and newer.
> Bugfix: Missing lock icons in vaults list
